### ISSUE TITLE
Play past shows

### ISSUE THREAD

**Issue by turkeyphant** [hugovk/bbcscrobbler#8]
Is there any way to make this scrobble past broadcasts?

**Comment by hugovk** [comment]
No, it only scrobbles what's being played right now on the same BBC station's Last.fm profile.

If you play past broadcasts via BBC Sounds on the web, you could try a browser extension like https://web-scrobbler.com/

**Comment by turkeyphant** [comment]
The problem with web scrobblers is that BBC Sounds seems to play the whole show as one "song" rather than the individual tracks.

**Comment by hugovk** [comment]
Thanks for the suggestion, but this is out of scope for bbcscrobbler,
